// Hospital Configuration
// Centralized settings for hospital data (departments, doctors, services, etc.)

export const HOSPITAL_CONFIG = {
  // Hospital Information
  name: 'CareHub Medical Center',
  tagline: 'Your Health, Our Priority',
  description: 'Leading healthcare provider with state-of-the-art facilities and expert medical professionals dedicated to providing exceptional patient care.',
  mission: 'To provide compassionate, quality healthcare services to our community while maintaining the highest standards of medical excellence.',
  vision: 'To be the premier healthcare institution recognized for innovation, excellence, and patient-centered care.',
  
  // Accreditations
  accreditations: [
    'Joint Commission International (JCI) Accredited',
    'ISO 9001:2015 Certified',
    'College of American Pathologists (CAP) Accredited',
    'American Heart Association Training Center',
  ],
  
  // Awards
  awards: [
    'Best Hospital in New York 2024',
    'Patient Safety Excellence Award',
    'Top 100 Hospitals in America',
    'Healthcare Quality Award',
  ],
} as const;

export const DEPARTMENTS = [
  {
    id: 'cardiology',
    name: 'Cardiology',
    description: 'Comprehensive heart care and cardiovascular treatments with advanced diagnostic and therapeutic procedures',
    icon: 'Heart',
    color: 'red',
    services: [
      'Cardiac Catheterization',
      'Echocardiography',
      'Stress Testing',
      'Heart Failure Management',
      'Arrhythmia Treatment',
      'Preventive Cardiology',
    ],
    facilities: [
      'State-of-the-art Cath Lab',
      '24/7 Emergency Cardiac Care',
      'Advanced Cardiac ICU',
      'Cardiac Rehabilitation Center',
    ],
  },
  {
    id: 'neurology',
    name: 'Neurology',
    description: 'Expert neurological care and brain health services with cutting-edge diagnostic technology',
    icon: 'Brain',
    color: 'purple',
    services: [
      'Stroke Care',
      'Epilepsy Management',
      'Movement Disorders',
      'Headache & Migraine Treatment',
      'Multiple Sclerosis Care',
      'Neuromuscular Disorders',
    ],
    facilities: [
      'Advanced MRI & CT Scanning',
      'EEG Laboratory',
      'Stroke Unit',
      'Neuro-rehabilitation Center',
    ],
  },
  {
    id: 'orthopedics',
    name: 'Orthopedics',
    description: 'Advanced bone and joint treatments including sports medicine and reconstructive surgery',
    icon: 'Bone',
    color: 'blue',
    services: [
      'Joint Replacement Surgery',
      'Sports Medicine',
      'Spine Surgery',
      'Trauma Care',
      'Arthroscopy',
      'Physical Therapy',
    ],
    facilities: [
      'Modern Operating Theaters',
      'Physical Therapy Gym',
      'Sports Medicine Clinic',
      'Orthopedic Trauma Center',
    ],
  },
  {
    id: 'pediatrics',
    name: 'Pediatrics',
    description: 'Specialized care for children and adolescents from birth through teenage years',
    icon: 'Baby',
    color: 'green',
    services: [
      'Well-Child Checkups',
      'Vaccinations',
      'Developmental Assessments',
      'Pediatric Emergency Care',
      'Adolescent Medicine',
      'Chronic Disease Management',
    ],
    facilities: [
      'Child-Friendly Clinic',
      'Pediatric Emergency Room',
      'NICU',
      'Pediatric ICU',
    ],
  },
  {
    id: 'emergency',
    name: 'Emergency Medicine',
    description: '24/7 emergency medical services with rapid response teams and trauma care',
    icon: 'Ambulance',
    color: 'orange',
    services: [
      'Trauma Care',
      'Cardiac Emergencies',
      'Stroke Care',
      'Emergency Surgery',
      'Poison Control',
      'Emergency Pediatrics',
    ],
    facilities: [
      '24/7 Emergency Department',
      'Trauma Center Level 1',
      'Helipad for Air Ambulance',
      'Fast Track Unit',
    ],
  },
  {
    id: 'radiology',
    name: 'Radiology',
    description: 'Advanced imaging and diagnostic services with latest technology',
    icon: 'ScanLine',
    color: 'teal',
    services: [
      'MRI Scanning',
      'CT Scanning',
      'X-Ray',
      'Ultrasound',
      'Mammography',
      'Interventional Radiology',
    ],
    facilities: [
      '3T MRI Scanner',
      '128-Slice CT Scanner',
      'Digital X-Ray Systems',
      'Interventional Suite',
    ],
  },
  {
    id: 'general-medicine',
    name: 'General Medicine',
    description: 'Comprehensive primary care and internal medicine services',
    icon: 'Stethoscope',
    color: 'indigo',
    services: [
      'Primary Care',
      'Chronic Disease Management',
      'Preventive Medicine',
      'Health Screenings',
      'Vaccination Programs',
      'Geriatric Care',
    ],
    facilities: [
      'Outpatient Clinics',
      'Health Screening Center',
      'Chronic Care Clinic',
      'Geriatric Ward',
    ],
  },
  {
    id: 'surgery',
    name: 'Surgical Services',
    description: 'Comprehensive surgical care with minimally invasive techniques',
    icon: 'Scissors',
    color: 'pink',
    services: [
      'General Surgery',
      'Laparoscopic Surgery',
      'Minimally Invasive Surgery',
      'Day Surgery',
      'Robotic Surgery',
      'Endoscopy',
    ],
    facilities: [
      'Modern Operating Rooms',
      'Day Surgery Unit',
      'Robotic Surgery Suite',
      'Post-Operative Care Unit',
    ],
  },
] as const;

export const SERVICES = [
  {
    id: 'emergency-care',
    title: 'Emergency Care',
    description: '24/7 emergency medical services with rapid response teams and advanced trauma care facilities',
    icon: 'Activity',
    features: [
      '24/7 Availability',
      'Trauma Center',
      'Emergency Ambulance',
      'Rapid Response Team',
    ],
  },
  {
    id: 'surgery',
    title: 'Surgery',
    description: 'Advanced surgical procedures with experienced surgeons and state-of-the-art operation theaters',
    icon: 'Scissors',
    features: [
      'General Surgery',
      'Minimally Invasive',
      'Robotic Surgery',
      'Day Surgery',
    ],
  },
  {
    id: 'diagnostics',
    title: 'Diagnostics',
    description: 'State-of-the-art diagnostic and imaging services including MRI, CT, X-Ray, and ultrasound',
    icon: 'Stethoscope',
    features: [
      'MRI & CT Scan',
      'X-Ray & Ultrasound',
      'Laboratory Tests',
      'Digital Imaging',
    ],
  },
  {
    id: 'pharmacy',
    title: 'Pharmacy',
    description: 'In-house pharmacy with prescription management and medication counseling services',
    icon: 'Pill',
    features: [
      '24/7 Pharmacy',
      'Prescription Refills',
      'Medication Counseling',
      'Home Delivery',
    ],
  },
  {
    id: 'laboratory',
    title: 'Laboratory',
    description: 'Comprehensive laboratory testing and analysis with fast turnaround times',
    icon: 'FlaskConical',
    features: [
      'Blood Tests',
      'Pathology',
      'Microbiology',
      'Quick Results',
    ],
  },
  {
    id: 'telemedicine',
    title: 'Telemedicine',
    description: 'Virtual consultations with medical professionals from the comfort of your home',
    icon: 'Video',
    features: [
      'Video Consultations',
      'Remote Monitoring',
      'E-Prescriptions',
      'Follow-up Care',
    ],
  },
] as const;

export const DOCTORS = [
  {
    id: '1',
    name: 'Dr. Sarah Johnson',
    specialty: 'Cardiologist',
    department: 'cardiology',
    experience: '15 years',
    education: 'MD, Harvard Medical School',
    qualifications: [
      'Board Certified Cardiologist',
      'Fellowship in Interventional Cardiology',
      'Advanced Cardiac Life Support (ACLS) Certified',
    ],
    languages: ['English', 'Spanish'],
    image: 'doctor female professional',
    bio: 'Dr. Sarah Johnson is a highly experienced cardiologist specializing in interventional cardiology and heart disease prevention.',
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Friday'],
  },
  {
    id: '2',
    name: 'Dr. Michael Chen',
    specialty: 'Neurologist',
    department: 'neurology',
    experience: '12 years',
    education: 'MD, Johns Hopkins University',
    qualifications: [
      'Board Certified Neurologist',
      'Specialty in Stroke Medicine',
      'Epilepsy Management Certification',
    ],
    languages: ['English', 'Mandarin'],
    image: 'doctor male professional',
    bio: 'Dr. Michael Chen specializes in stroke care and neurological disorders with a focus on innovative treatment approaches.',
    availability: ['Monday', 'Wednesday', 'Thursday', 'Friday'],
  },
  {
    id: '3',
    name: 'Dr. Emily Rodriguez',
    specialty: 'Pediatrician',
    department: 'pediatrics',
    experience: '10 years',
    education: 'MD, Stanford University',
    qualifications: [
      'Board Certified Pediatrician',
      'Pediatric Advanced Life Support (PALS)',
      'Developmental Pediatrics Fellowship',
    ],
    languages: ['English', 'Spanish', 'Portuguese'],
    image: 'doctor female professional',
    bio: 'Dr. Emily Rodriguez is dedicated to providing comprehensive pediatric care with a warm and caring approach.',
    availability: ['Monday', 'Tuesday', 'Thursday', 'Friday'],
  },
  {
    id: '4',
    name: 'Dr. James Wilson',
    specialty: 'Orthopedic Surgeon',
    department: 'orthopedics',
    experience: '18 years',
    education: 'MD, Mayo Clinic',
    qualifications: [
      'Board Certified Orthopedic Surgeon',
      'Fellowship in Sports Medicine',
      'Joint Replacement Specialist',
    ],
    languages: ['English'],
    image: 'doctor male professional',
    bio: 'Dr. James Wilson is an expert orthopedic surgeon specializing in joint replacement and sports medicine.',
    availability: ['Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  },
  {
    id: '5',
    name: 'Dr. Robert Davis',
    specialty: 'General Surgeon',
    department: 'surgery',
    experience: '20 years',
    education: 'MD, Columbia University',
    qualifications: [
      'Board Certified General Surgeon',
      'Minimally Invasive Surgery Expert',
      'Robotic Surgery Certification',
    ],
    languages: ['English', 'French'],
    image: 'doctor male professional',
    bio: 'Dr. Robert Davis has extensive experience in general and minimally invasive surgery techniques.',
    availability: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
  },
  {
    id: '6',
    name: 'Dr. Emily Williams',
    specialty: 'Pediatric Specialist',
    department: 'pediatrics',
    experience: '14 years',
    education: 'MD, Yale School of Medicine',
    qualifications: [
      'Board Certified Pediatrician',
      'Neonatal Care Specialist',
      'Pediatric Emergency Medicine',
    ],
    languages: ['English', 'German'],
    image: 'doctor female professional',
    bio: 'Dr. Emily Williams provides expert pediatric care with special focus on neonatal and emergency medicine.',
    availability: ['Monday', 'Wednesday', 'Thursday', 'Saturday'],
  },
] as const;

export const TESTIMONIALS = [
  {
    id: '1',
    name: 'John Anderson',
    text: 'The care I received was exceptional. The staff was professional and caring throughout my treatment. I highly recommend CareHub Medical Center.',
    rating: 5,
    date: '2024-01-15',
    department: 'Cardiology',
    treatment: 'Cardiac Surgery',
  },
  {
    id: '2',
    name: 'Maria Garcia',
    text: 'Dr. Johnson and her team saved my life. I cannot thank them enough for their expertise and dedication. The facilities are world-class.',
    rating: 5,
    date: '2024-02-20',
    department: 'Cardiology',
    treatment: 'Heart Treatment',
  },
  {
    id: '3',
    name: 'Robert Kim',
    text: 'Modern facilities, excellent doctors, and friendly staff. Highly recommend CareHub Medical Center for anyone seeking quality healthcare.',
    rating: 5,
    date: '2024-03-10',
    department: 'Orthopedics',
    treatment: 'Joint Replacement',
  },
  {
    id: '4',
    name: 'Lisa Thompson',
    text: 'Outstanding pediatric care for my daughter. Dr. Rodriguez is amazing with children and very knowledgeable. Thank you CareHub!',
    rating: 5,
    date: '2024-04-05',
    department: 'Pediatrics',
    treatment: 'Pediatric Care',
  },
  {
    id: '5',
    name: 'David Miller',
    text: 'The emergency department responded quickly and professionally. The doctors and nurses were excellent during a stressful time.',
    rating: 5,
    date: '2024-05-12',
    department: 'Emergency',
    treatment: 'Emergency Care',
  },
] as const;

// Type exports
export type Department = typeof DEPARTMENTS[number];
export type Service = typeof SERVICES[number];
export type Doctor = typeof DOCTORS[number];
export type Testimonial = typeof TESTIMONIALS[number];
