/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wkbxjsnjhrhnhcsnkfsr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrYnhqc25qaHJobmhjc25rZnNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4ODMzNjAsImV4cCI6MjA3NjQ1OTM2MH0.qFEznf66-XPPCh6qAHXLV9Niphx0-cwnWCHKfqZGqyA"